### ISSUE TITLE
expanding of text box

### ISSUE THREAD

**Issue by nazneennahar** [UltimaBGD/micro-note#1]
Hey i was looking through your app.It looks amazing but while i was typing sentences down the text box would't expand and this makes it hard for read thing by scrolling all the time 

i will like to fix the text box and expand it .

**Comment by UltimaBGD** [comment]
That sounds good, go ahead!

**Comment by nazneennahar** [comment]
Thank you so much.

**Comment by UltimaBGD** [comment]
Closed via #4
