### ISSUE TITLE
Set the cursor on the textarea on the load

### ISSUE THREAD

**Issue by birtony** [UltimaBGD/micro-note#5]
Hello Brett,

I think you have completed a really good job in implementing the Note Saver!
One thing that I noticed while testing it is that the textarea container does not automatically set the cursor on it. I believe it would be great to let the user start typing from the moment he opens your app.

Let me try to fix this for you.

**Comment by UltimaBGD** [comment]
Go ahead!

**Comment by nazneennahar** [comment]
Sure go ahead

Sent from my iPhone

On 23 Sep 2019, at 22:55, Anton Biriukov <notifications@github.com> wrote:

﻿

Hello Brett,

I think you have completed a really good job in implementing the Note Saver!
One thing that I noticed while testing it is that the textarea container can expand beyond the borders of its parent container. I believe it would be great to prevent it from doing so.

Let me try to fix this for you.

**Comment by UltimaBGD** [comment]
Closed via #6,
Thank you!
